version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - 
     
      - echo Build started on `date`
      
      - echo Building the Docker image...          
      - 
      
      - echo Build completed on `date`
      - 
      
      - echo Pushing the Docker image...
      - 
    
     
  
      
      
